# Generated by Django 5.0.6 on 2025-10-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=100)),
                ('attack_type', models.CharField(choices=[('SQLI', 'SQL Injection'), ('DDoS', 'DDoS'), ('BruteForce', 'Brute Force'), ('PortScan', 'Port Scan'), ('XSS', 'Cross-Site Scripting')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
