# Generated by Django 5.0.6 on 2025-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='source',
            field=models.CharField(choices=[('Network', 'Network Honeypot'), ('Website', 'Website Honeypot'), ('Keylogger', 'Keylogger')], default='Network', max_length=10),
        ),
    ]
