# Generated by Django 5.0.6 on 2025-10-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_simulator', '0002_attacklog_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='captured_data',
            field=models.CharField(blank=True, help_text='The actual keystrokes or data captured.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='target_context',
            field=models.CharField(blank=True, help_text='The field or area where data was captured (e.g., username field).', max_length=100, null=True),
        ),
    ]
