# Generated by Django 5.0.6 on 2025-10-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attack_simulator', '0003_attacklog_captured_data_attacklog_target_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacklog',
            name='attack_type',
            field=models.CharField(choices=[('SQLI', 'SQL Injection'), ('XSS', 'Cross-Site Scripting'), ('CSRF', 'Cross-Site Request Forgery'), ('DIR_TRAV', 'Directory Traversal'), ('CMD_INJ', 'Command Injection'), ('FILE_INC', 'File Inclusion'), ('XXE', 'XML External Entity'), ('BRUTEFORCE', 'Brute Force'), ('PORTSCAN', 'Port Scan'), ('SNIFFING', 'Packet Sniffing'), ('MITM', 'Man-in-the-Middle'), ('RECON', 'Network Reconnaissance'), ('MALWARE_PROP', 'Malware Propagation'), ('KEYLOGGING', 'Keylogging'), ('CRED_HARVEST', 'Credential Harvesting'), ('DATA_EXFIL', 'Data Exfiltration'), ('SCREEN_CAP', 'Screen Capture'), ('DDOS', 'DDoS'), ('OTHER', 'Other Suspicious Activity')], max_length=15),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='captured_data',
            field=models.CharField(blank=True, help_text='Description or data related to the attack.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attacklog',
            name='target_context',
            field=models.CharField(blank=True, help_text='The field, service, or area targeted.', max_length=100, null=True),
        ),
    ]
